<?php

namespace ContainerX6VBufk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W2D3KKvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w2D3KKv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w2D3KKv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'personaRepository' => ['privates', 'App\\Repository\\PersonaRepository', 'getPersonaRepositoryService', true],
            'tableFactory' => ['services', 'hello_sebastian_hello_bootstrap_table.hello_bootstrap_table_factory', 'getHelloSebastianHelloBootstrapTable_HelloBootstrapTableFactoryService', true],
        ], [
            'personaRepository' => 'App\\Repository\\PersonaRepository',
            'tableFactory' => '?',
        ]);
    }
}
