<?php

namespace ContainerX6VBufk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I8pTGkDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i8pTGkD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i8pTGkD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pago' => ['privates', '.errored..service_locator.i8pTGkD.App\\Entity\\Pago', NULL, 'Cannot autowire service ".service_locator.i8pTGkD": it needs an instance of "App\\Entity\\Pago" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pago' => 'App\\Entity\\Pago',
        ]);
    }
}
