<?php

namespace ContainerX6VBufk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O8cr5H9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O8cr5H9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O8cr5H9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pago' => ['privates', '.errored..service_locator.O8cr5H9.App\\Entity\\Pago', NULL, 'Cannot autowire service ".service_locator.O8cr5H9": it needs an instance of "App\\Entity\\Pago" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'pago' => 'App\\Entity\\Pago',
        ]);
    }
}
