<?php

namespace ContainerX6VBufk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGu7YFfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PGu7YFf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PGu7YFf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActividadController::delete' => ['privates', '.service_locator._7RcCzS', 'get_ServiceLocator_7RcCzSService', true],
            'App\\Controller\\ActividadController::edit' => ['privates', '.service_locator._7RcCzS', 'get_ServiceLocator_7RcCzSService', true],
            'App\\Controller\\ActividadController::index' => ['privates', '.service_locator.KKaXMJD', 'get_ServiceLocator_KKaXMJDService', true],
            'App\\Controller\\ActividadController::new' => ['privates', '.service_locator.e1d_HoN', 'get_ServiceLocator_E1dHoNService', true],
            'App\\Controller\\ActividadController::show' => ['privates', '.service_locator.XqleNDd', 'get_ServiceLocator_XqleNDdService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\PagoController::delete' => ['privates', '.service_locator.O8cr5H9', 'get_ServiceLocator_O8cr5H9Service', true],
            'App\\Controller\\PagoController::edit' => ['privates', '.service_locator.O8cr5H9', 'get_ServiceLocator_O8cr5H9Service', true],
            'App\\Controller\\PagoController::index' => ['privates', '.service_locator.P2813pf', 'get_ServiceLocator_P2813pfService', true],
            'App\\Controller\\PagoController::new' => ['privates', '.service_locator.QtcC3n6', 'get_ServiceLocator_QtcC3n6Service', true],
            'App\\Controller\\PagoController::show' => ['privates', '.service_locator.i8pTGkD', 'get_ServiceLocator_I8pTGkDService', true],
            'App\\Controller\\PersonaController::delete' => ['privates', '.service_locator.1_lwwy4', 'get_ServiceLocator_1Lwwy4Service', true],
            'App\\Controller\\PersonaController::edit' => ['privates', '.service_locator.1_lwwy4', 'get_ServiceLocator_1Lwwy4Service', true],
            'App\\Controller\\PersonaController::index' => ['privates', '.service_locator.w2D3KKv', 'get_ServiceLocator_W2D3KKvService', true],
            'App\\Controller\\PersonaController::new' => ['privates', '.service_locator.rMfJu_5', 'get_ServiceLocator_RMfJu5Service', true],
            'App\\Controller\\PersonaController::show' => ['privates', '.service_locator.dV9IGeb', 'get_ServiceLocator_DV9IGebService', true],
            'App\\Controller\\UserController::changeState' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.1Q2KOXP', 'get_ServiceLocator_1Q2KOXPService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.NVwIQPd', 'get_ServiceLocator_NVwIQPdService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.l8nzxEW', 'get_ServiceLocator_L8nzxEWService', true],
            'App\\Controller\\UserController::profile' => ['privates', '.service_locator.UgnwfXp', 'get_ServiceLocator_UgnwfXpService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ActividadController:delete' => ['privates', '.service_locator._7RcCzS', 'get_ServiceLocator_7RcCzSService', true],
            'App\\Controller\\ActividadController:edit' => ['privates', '.service_locator._7RcCzS', 'get_ServiceLocator_7RcCzSService', true],
            'App\\Controller\\ActividadController:index' => ['privates', '.service_locator.KKaXMJD', 'get_ServiceLocator_KKaXMJDService', true],
            'App\\Controller\\ActividadController:new' => ['privates', '.service_locator.e1d_HoN', 'get_ServiceLocator_E1dHoNService', true],
            'App\\Controller\\ActividadController:show' => ['privates', '.service_locator.XqleNDd', 'get_ServiceLocator_XqleNDdService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\PagoController:delete' => ['privates', '.service_locator.O8cr5H9', 'get_ServiceLocator_O8cr5H9Service', true],
            'App\\Controller\\PagoController:edit' => ['privates', '.service_locator.O8cr5H9', 'get_ServiceLocator_O8cr5H9Service', true],
            'App\\Controller\\PagoController:index' => ['privates', '.service_locator.P2813pf', 'get_ServiceLocator_P2813pfService', true],
            'App\\Controller\\PagoController:new' => ['privates', '.service_locator.QtcC3n6', 'get_ServiceLocator_QtcC3n6Service', true],
            'App\\Controller\\PagoController:show' => ['privates', '.service_locator.i8pTGkD', 'get_ServiceLocator_I8pTGkDService', true],
            'App\\Controller\\PersonaController:delete' => ['privates', '.service_locator.1_lwwy4', 'get_ServiceLocator_1Lwwy4Service', true],
            'App\\Controller\\PersonaController:edit' => ['privates', '.service_locator.1_lwwy4', 'get_ServiceLocator_1Lwwy4Service', true],
            'App\\Controller\\PersonaController:index' => ['privates', '.service_locator.w2D3KKv', 'get_ServiceLocator_W2D3KKvService', true],
            'App\\Controller\\PersonaController:new' => ['privates', '.service_locator.rMfJu_5', 'get_ServiceLocator_RMfJu5Service', true],
            'App\\Controller\\PersonaController:show' => ['privates', '.service_locator.dV9IGeb', 'get_ServiceLocator_DV9IGebService', true],
            'App\\Controller\\UserController:changeState' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.1Q2KOXP', 'get_ServiceLocator_1Q2KOXPService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.NVwIQPd', 'get_ServiceLocator_NVwIQPdService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.l8nzxEW', 'get_ServiceLocator_L8nzxEWService', true],
            'App\\Controller\\UserController:profile' => ['privates', '.service_locator.UgnwfXp', 'get_ServiceLocator_UgnwfXpService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ActividadController::delete' => '?',
            'App\\Controller\\ActividadController::edit' => '?',
            'App\\Controller\\ActividadController::index' => '?',
            'App\\Controller\\ActividadController::new' => '?',
            'App\\Controller\\ActividadController::show' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\PagoController::delete' => '?',
            'App\\Controller\\PagoController::edit' => '?',
            'App\\Controller\\PagoController::index' => '?',
            'App\\Controller\\PagoController::new' => '?',
            'App\\Controller\\PagoController::show' => '?',
            'App\\Controller\\PersonaController::delete' => '?',
            'App\\Controller\\PersonaController::edit' => '?',
            'App\\Controller\\PersonaController::index' => '?',
            'App\\Controller\\PersonaController::new' => '?',
            'App\\Controller\\PersonaController::show' => '?',
            'App\\Controller\\UserController::changeState' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::profile' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ActividadController:delete' => '?',
            'App\\Controller\\ActividadController:edit' => '?',
            'App\\Controller\\ActividadController:index' => '?',
            'App\\Controller\\ActividadController:new' => '?',
            'App\\Controller\\ActividadController:show' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\PagoController:delete' => '?',
            'App\\Controller\\PagoController:edit' => '?',
            'App\\Controller\\PagoController:index' => '?',
            'App\\Controller\\PagoController:new' => '?',
            'App\\Controller\\PagoController:show' => '?',
            'App\\Controller\\PersonaController:delete' => '?',
            'App\\Controller\\PersonaController:edit' => '?',
            'App\\Controller\\PersonaController:index' => '?',
            'App\\Controller\\PersonaController:new' => '?',
            'App\\Controller\\PersonaController:show' => '?',
            'App\\Controller\\UserController:changeState' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:profile' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
