<?php

namespace ContainerX6VBufk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActividadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XqleNDd.App\Entity\Actividad' shared service.
     *
     * @return \App\Entity\Actividad
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XqleNDd": it needs an instance of "App\\Entity\\Actividad" but this type has been excluded in "config/services.yaml".');
    }
}
