<?php

namespace ContainerX6VBufk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActividadControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ActividadController' shared autowired service.
     *
     * @return \App\Controller\ActividadController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ActividadController.php';

        $container->services['App\\Controller\\ActividadController'] = $instance = new \App\Controller\ActividadController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\ActividadController', $container));

        return $instance;
    }
}
