version: '3.6'
services:
    php:
        # image: registry.gitlab.com/min-jus-gba-informatica-global/min-jus-gba-informatica/ddhh/mesa-de-gestion-democratica-y-violencia-institucional/php:0.0.1
        build:
            context: .
            dockerfile: docker/Dockerfile.php
        depends_on:
            database:
                condition: service_healthy
        env_file:
        - .env
        # - stack.env
        environment:
            - APP_ENV=prod
        
    nginx:
        # image: registry.gitlab.com/min-jus-gba-informatica-global/min-jus-gba-informatica/ddhh/mesa-de-gestion-democratica-y-violencia-institucional/nginx:0.0.1
        build:
            context: .
            dockerfile: docker/Dockerfile.nginx
        depends_on:
        - php
        ports:
            - "8008:80"
        environment:
            VIRTUAL_HOST: localhost
            # VIRTUAL_HOST: gcc.mjus.gba.gob.ar
            # CERT_NAME: _.mjus.gba.gob.ar

        # networks:
        # - nginx-proxy
        # - default
    database:
        image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=vi
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
        volumes:
        - symfony-db:/var/lib/mysql:rw,delegated
        # - ./bases/vi.sql:/docker-entrypoint-initdb.d/dump.sql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
            timeout: 20s
            retries: 10
    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=user
            - PMA_PASSWORD=pass
            - MYSQL_ROOT_PASSWORD=root
volumes:
  symfony-db:

# networks:
#     nginx-proxy:
#       external: true
#     default: