ARG NGINX_VERSION=1.15

FROM nginx:${NGINX_VERSION}-alpine AS symfony_nginx

RUN apk add --update --no-cache tzdata;

WORKDIR /srv/symfony

COPY docker/nginx/app.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf

ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY public ./public