<?php

namespace ContainerXSz2oXp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P2813pfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P2813pf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P2813pf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pagoRepository' => ['privates', 'App\\Repository\\PagoRepository', 'getPagoRepositoryService', true],
            'tableFactory' => ['services', 'hello_sebastian_hello_bootstrap_table.hello_bootstrap_table_factory', 'getHelloSebastianHelloBootstrapTable_HelloBootstrapTableFactoryService', true],
        ], [
            'pagoRepository' => 'App\\Repository\\PagoRepository',
            'tableFactory' => '?',
        ]);
    }
}
