<?php

namespace ContainerXSz2oXp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCargaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CargaType' shared autowired service.
     *
     * @return \App\Form\CargaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CargaType.php';

        return $container->privates['App\\Form\\CargaType'] = new \App\Form\CargaType();
    }
}
