<?php

namespace ContainerXSz2oXp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O8cr5H9.App\Entity\Pago' shared service.
     *
     * @return \App\Entity\Pago
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O8cr5H9": it needs an instance of "App\\Entity\\Pago" but this type has been excluded in "config/services.yaml".');
    }
}
